### ISSUE TITLE
Cannot clone repository on Windows

### ISSUE THREAD

**Issue by kalevivt** [nbeversl/urtext-sublime#1]
Cannot clone the repository on Windows due to pipe characters in documentation filenames.

**Comment by nbeversl** [comment]
Pipe characters are removed from the documentation, and from all file renaming features, in [0.1.12-alpha](https://github.com/nbeversl/urtext-sublime/releases/tag/0.1.12-alpha)

**Comment by nbeversl** [comment]
Note a similar issue results with colons, fixed in [0.1.13-alpha](https://github.com/nbeversl/urtext-sublime/releases/tag/0.1.13-alpha).
